fix(upgrad engine) Prompt message when upgrading engine automatically
longhorn/longhorn-ui pull request #363
Opened 2021-03-04 03:37 UTC by smallteeths

https://github.com/longhorn/longhorn/issues/2281

Signed-off-by: Siye Wang <siye@rancher.com>

2021-03-06 01:59 UTC, PhanLe1010 requested changes

2021-03-06 01:59 UTC, PhanLe1010 commented on src/utils/status.js
> +}
To determine whether a volume is upgrading, we only need to check `volume. engineImage  != volume. currentImage`
We don't need to compare it to the `defaultEngineImage`

```
export function statusUpgradingEngine(volume) {
   if (volume && volume. engineImage && volume. currentImage) {
      return volume. engineImage  != volume. currentImage
   }
   return false
 }
```

2021-03-06 01:59 UTC, PhanLe1010 commented on src/utils/status.js
> +}
This is the condition to show the global notification. We don't need this to check if an individual volume is upgrading.

2021-03-06 02:41 UTC, PhanLe1010 requested changes

2021-03-06 02:41 UTC, PhanLe1010 commented on src/utils/status.js
> +}
```
const isUpgradingEngine = (volume) => {
   if (volume && volume.engineImage && volume.currentImage) {
      return volume.engineImage  != volume.currentImage
   }
   return false
 }

export function statusUpgradingEngine(volume) {
   if (isUpgradingEngine(volume)) {
     return (<Tooltip title={`Upgrading engine from ${volume.engineImage} to ${volume.currentImage}`}><Icon style={{ marginRight: 5 }} type="sync" spin /></Tooltip>)
   }
   return ''
 }
```

2021-03-08 18:43 UTC, PhanLe1010 approved these changes
LGTM

2021-03-08 18:47 UTC, yasker approved these changes
Approve on behavior of @PhanLe1010

2021-03-08 18:47 UTC, merged