[WIP] feat(footer) Add Stable Longhorn Versions information display
longhorn/longhorn-ui pull request #442
Opened 2021-09-22 08:31 UTC by smallteeths

https://github.com/longhorn/longhorn/issues/3032

Signed-off-by: Siye Wang <siye@rancher.com>

2021-09-22 20:48 UTC, PhanLe1010 commented on src/components/Layout/Footer.js
> +          <a target="blank" onClick={showStableLonghornVersions}>{`Stable Longhorn Versions (${stableLonghornVersions})`}</a>
Can we change the text `Stable Longhorn Versions` to `Newer Stable Versions` ?

2021-09-22 21:01 UTC, PhanLe1010 requested changes
We only want to show the stable versions that are newer than the current version. If there is no newer stable version, we don't show the `stable versions` list on the bottom of the page.

2021-09-23 20:43 UTC, PhanLe1010 approved these changes
LGTM. Thanks @smallteeths !

2021-09-24 01:10 UTC, innobead approved these changes
LGTM, but it seems we can't do the filtering of the latest stable versions in the setting page but do in the footer.

But, It's good for now.

2021-09-24 01:10 UTC, merged

2021-09-24 01:10 UTC, innobead commented
@smallteeths Please help backport to 1.2.x.

2021-09-24 01:59 UTC, PhanLe1010 commented
@innobead Can we also backport to v1.1.3 ?

2021-09-24 02:13 UTC, innobead commented
> @innobead Can we also backport to v1.1.3 ?

We should. :)