[WIP] Feat(System backup) Support longhorn system backup/restore
longhorn/longhorn-ui pull request #547
Opened 2022-11-22 10:10 UTC by smallteeths

https://github.com/longhorn/longhorn/issues/4855
<img width="1775" alt="截屏2022-11-22 下午6 09 38" src="https://user-images.githubusercontent.com/27733391/203286882-58b8ea1f-01c6-4d78-acc4-89bcf3a5d8a5.png">

Signed-off-by: Siye Wang <siye@rancher.com>

2022-12-08 14:13 UTC, innobead requested changes
In genreal, LGTM.

2022-12-08 14:54 UTC, c3y1huang requested changes

2022-12-08 14:54 UTC, c3y1huang commented on src/routes/systemBackups/systemBackupsBulkActions.js
> +          title: `Are you sure you want to delete System Buckups ${selectedRows.map(item => item.name).join(',')} ?`,
```suggestion
          title: `Are you sure you want to delete System Backups ${selectedRows.map(item => item.name).join(',')} ?`,
```

2022-12-08 14:54 UTC, c3y1huang commented on src/routes/systemBackups/systemBackupsBulkActions.js
> +  deleteSystemBuckups: PropTypes.func,
deleteSystemBuckups

2022-12-08 14:54 UTC, c3y1huang commented on src/routes/systemBackups/systemBackupsBulkActions.js
> +  createSystemBuckup: PropTypes.func,
createSystemBackup

2022-12-09 03:11 UTC, smallteeths commented on src/routes/systemBackups/createSystemRestore.js
> +                message: 'Please input System backup image.',
done

2022-12-09 03:12 UTC, smallteeths commented on src/utils/page.js
> +  if (key === 'systemBackupSize' || key === 'systemBackupSize') {
done

2022-12-09 03:12 UTC, smallteeths commented on src/routes/systemBackups/systemBackupsBulkActions.js
> +          title: `Are you sure you want to delete System Buckups ${selectedRows.map(item => item.name).join(',')} ?`,
done

2022-12-09 03:12 UTC, smallteeths commented on src/routes/systemBackups/systemBackupsBulkActions.js
> +  deleteSystemBuckups: PropTypes.func,
done

2022-12-09 03:12 UTC, smallteeths commented on src/routes/systemBackups/systemBackupsBulkActions.js
> +  createSystemBuckup: PropTypes.func,
done

2022-12-09 03:34 UTC, innobead approved these changes

2022-12-09 03:34 UTC, merged